### ISSUE TITLE
3 sessy's

### ISSUE THREAD

**Issue by sideriusj** [JanJaapKo/SessyBattery#2]
Ik heb de file aangepast, maar krijg nu deze  foutmeldingen:

2024-11-30 22:43:16.193 Error: Sessy: Call to function 'onStart' failed, exception details:
2024-11-30 22:43:16.216 Error: Sessy: Traceback (most recent call last):
2024-11-30 22:43:16.216 Error: Sessy: File "/home/pi/domoticz/plugins/SessyBattery/plugin.py", line 441, in onStart
2024-11-30 22:43:16.216 Error: Sessy: _plugin.onStart()
2024-11-30 22:43:16.216 Error: Sessy: File "/home/pi/domoticz/plugins/SessyBattery/plugin.py", line 151, in onStart
2024-11-30 22:43:16.216 Error: Sessy: config_map = json.load(f)
2024-11-30 22:43:16.216 Error: Sessy: ^^^^^^^^^^^^
2024-11-30 22:43:16.216 Error: Sessy: File "/usr/lib/python3.11/json/__init__.py", line 293, in load
2024-11-30 22:43:16.216 Error: Sessy: return loads(fp.read(),
2024-11-30 22:43:16.216 Error: Sessy: ^^^^^^^^^^^^^^^^
2024-11-30 22:43:16.216 Error: Sessy: File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
2024-11-30 22:43:16.216 Error: Sessy: return _default_decoder.decode(s)
2024-11-30 22:43:16.216 Error: Sessy: ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-30 22:43:16.216 Error: Sessy: File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
2024-11-30 22:43:16.216 Error: Sessy: obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2024-11-30 22:43:16.216 Error: Sessy: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-30 22:43:16.216 Error: Sessy: File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
2024-11-30 22:43:16.216 Error: Sessy: obj, end = self.scan_once(s, idx)
2024-11-30 22:43:16.216 Error: Sessy: ^^^^^^^^^^^^^^^^^^^^^^
2024-11-30 22:43:16.216 Error: Sessy: json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 4 column 33 (char 58)
2024-11-30 22:44:14.066 Error: Sessy: Call to function 'onHeartbeat' failed, exception details:
2024-11-30 22:44:14.069 Error: Sessy: Traceback (most recent call last):
2024-11-30 22:44:14.069 Error: Sessy: File "/home/pi/domoticz/plugins/SessyBattery/plugin.py", line 469, in onHeartbeat
2024-11-30 22:44:14.069 Error: Sessy: _plugin.onHeartbeat()
2024-11-30 22:44:14.069 Error: Sessy: File "/home/pi/domoticz/plugins/SessyBattery/plugin.py", line 189, in onHeartbeat
2024-11-30 22:44:14.069 Error: Sessy: for battery in self.devices_dict:
2024-11-30 22:44:14.070 Error: Sessy: ^^^^^^^^^^^^^^^^^
2024-11-30 22:44:14.070 Error: Sessy: AttributeError: 'SessyBatteryPlugin' object has no attribute 'devices_dict'

**Comment by JanJaapKo** [comment]
OK the root-cause error is a JSON syntax error as indicated in the log: 
 2024-11-30 22:43:16.216 Error: Sessy: json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 4 column 33 (char 58)

I'll add a prevention to the follow-up errors

**Comment by JanJaapKo** [comment]
Change pushed, please check

**Comment by JanJaapKo** [comment]
closing assuming no more issue
